# Generated by Django 4.1.7 on 2023-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_complaint_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location", models.CharField(max_length=255)),
            ],
        ),
    ]
