# Generated by Django 4.1.7 on 2023-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
    ]
